### Hi there, I'm Tran Nhat Thanh (aka dajneem23) 👋

<img src="https://komarev.com/ghpvc/?username=dajneem23" alt="Profile view" />

#### 📕 About me

- ✝️ I'm a Protestant, developer, blogger, and open-source maintainer & contributor!
- 🇻🇳 My Vietnamese name is Tran Nhat Thanh, but you can call me Thanh Tran.
- 🔭 I’m currently working on personal projects!
- 🌱 I’m currently learning English, Javascript, and full-stacks!
- 👯 I’m looking to collaborate with other developers building open-source projects for fun and learning!
- 💬 Ask me about everything, however, I'm not sure I will have the answers you need! 😂
#### 👷 Check out what I'm currently working on

{{range recentContributions 5}}
- [{{.Repo.Name}}]({{.Repo.URL}}){{with .Repo.Description}} - {{.}}{{end}} ({{humanize .OccurredAt}})
{{- end}}

#### 🌱 My latest projects
{{range recentRepos 5}}
- [{{.Name}}]({{.URL}}){{with .Description}} - {{.}}{{end}}
{{- end}}

#### 🔭 Latest releases I've contributed to
{{range recentReleases 5}}
- [{{.Name}}]({{.URL}}) ([{{.LastRelease.TagName}}]({{.LastRelease.URL}}), {{humanize .LastRelease.PublishedAt}}){{with .Description}} - {{.}}{{end}}
{{- end}}

#### 🔨 Latest Pull Requests I published
{{range recentPullRequests 5}}
- [{{.Title}}]({{.URL}}) on [{{.Repo.Name}}]({{.Repo.URL}}) ({{humanize .CreatedAt}})
{{- end}}

#### 📜 My recent blog posts

<!-- BLOG-POST-LIST:START --><!-- BLOG-POST-LIST:END -->

#### Coding statistics

<img
  src="https://github-profile-summary-cards.vercel.app/api/cards/stats?username=dajneem23&theme=github_dark"
  style="display: inline; width: 320px;"
/>
<img
  src="https://github-profile-summary-cards.vercel.app/api/cards/productive-time?username=dajneem23&theme=github_dark&utcOffset=7"
  style="display: inline; width: 320px;"
/>
<br />
<img
  src="https://github-profile-summary-cards.vercel.app/api/cards/repos-per-language?username=dajneem23&theme=github_dark"
  style="display: inline; width: 320px;"
/>
<img
  src="https://github-profile-summary-cards.vercel.app/api/cards/most-commit-language?username=dajneem23&theme=github_dark"
  style="display: inline; width: 320px;"
/>

#### How to contact me?

<a href="mailto:dajneem23@gmail.com">
 <img align="left" width="32px" src="https://img.icons8.com/fluency/32/gmail-new.png"    alt="dajneem23 | Email" />
</a>
[<img align="left" width="32px" src="https://img.icons8.com/fluency/32/github.png"       alt="dajneem23 | GitHub" />][github]
[<img align="left" width="32px" src="https://img.icons8.com/fluency/32/telegram-app.png" alt="dajneem23 | Telegram" />][telegram]
[<img align="left" width="32px" src="https://img.icons8.com/fluency/32/facebook.png"     alt="dajneem23 | Facebook" />][facebook]
[<img align="left" width="32px" src="https://img.icons8.com/fluency/32/linkedin.png"     alt="dajneem23 | LinkedIn" />][linkedin]
[<img align="left" width="32px" src="https://img.icons8.com/fluency/32/reddit.png"       alt="dajneem23 | Reddit" />][reddit]
[<img align="left" width="32px" src="https://img.icons8.com/fluency/32/twitter.png"      alt="dajneem23 | Twitter" />][twitter]

<br/>
<br/>


#### How to donate to me?

[<img align="left" height="32px" src="https://www.paypalobjects.com/paypal-ui/logos/svg/paypal-color.svg"  alt="Donate dajneem23 via Paypal" />][paypal]
[<img align="left" height="32px" src="https://storage.ko-fi.com/cdn/brandasset/kofi_bg_tag_white.png"      alt="Donate dajneem23 via  Ko-fi" />][kofi]
[<img align="left" height="32px" src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png"          alt="Donate dajneem23 via Buymeacoffee" />][buymeacoffee]
[<img align="left" height="32px" src="https://upload.wikimedia.org/wikipedia/vi/f/fe/MoMo_Logo.png"         alt="Donate dajneem23 via Momo" />][momo]
<br/>
<br/>

[website]: https://dajneem23.xyz/?utm_source=github&utm_medium=readme
[email]: dajneem23@gmail.com
[github]: https://github.com/dajneem23
[facebook]: https://facebook.com/leminhtri.py
[telegram]: https://t.me/dajneem23
[twitter]: https://twitter.com/dajneem23
[linkedin]: https://linkedin.com/in/tri-le-minh-1b05bb51/
[reddit]: https://reddit.com/u/dajneem23
[paypal]: https://paypal.me/dajneem23
[kofi]: https://ko-fi.com/dajneem23
[buymeacoffee]: https://buymeacoffee.com/dajneem23
[momo]: https://me.momo.vn/dajneem23

<br/>
<br/>

<details>
  <summary>My personal GitHub Metrics</summary>
  <br/>
  <img src="./github_metrics_01.svg" />
  <img src="./github_metrics_02.svg" />
</details>

### LICENSE

This source code is available under the [MIT LICENSE](/LICENSE).

Feel free to fork/clone this repository, however, please adjust the template to generate your own content, especially the profile view link.

Finally, don't just fork/clone it. Please give it a star :star2:!

<sub>Auto-generated by [markscribe](https://github.com/muesli/markscribe).</sub>
